### ISSUE TITLE
suddenly stops cutting

### ISSUE THREAD

**Issue by leonardojc** [LaosLaser/Firmware#49]
Hi everyone!.
I have a problem, since Laoslaser-14-11-2014.bin upgrade, the machine suddenly stops cutting.
Same with the version Laoslaser-23-02-2015.bin
but instead everything works fine with Laoslaser-10.26.2014 version.
could you please help me?
(sorry my english)
Thanks!

**Comment by jrv** [comment]
Problems like these are usually caused by interfering libraries. That makes it very hard to debug. Problems might show up in one release and be gone in the next, without related change in the laos software. 

Since debugging older versions is a waste of time, please upgrade to the latest version first and see what that does.

**Comment by leonardojc** [comment]
Jrv, thanks for your answer, but the version that best works for me is the 11/14/2014.
with the other, the machine stops at any time.
I do not know if someone else happens this
The strange thing is, it stops at any time. and not always in the same place at the same job.

regards

**Comment by jrv** [comment]
Sorry Leonardo, but we cannot give support on older versions. We are all volunteers, and I'm pretty sure nobody is volunteering to do research in versions that are outdated. 

If your machine stops any time with the latest firmware, please file an issue about that. Include an example file and description of what happens and when, so developers can check if that also happens with their machine. 

I think you will get more response if you document your problems on the Laoslaser forum then by posting it as an issue on GitHub.
